### ISSUE TITLE
Unmet Dependency

### ISSUE THREAD

**Issue by kason-i** [henkelmax/voicechat-interaction#1]
**Bug description**
I might be an idiot but I am running into an unmet dependency error. Unmet dependency on server launch. States 0.55.1 but I can not find that version anywhere. Everything works when vcinteraction is not installed. Thanks in advance!

**Steps to reproduce the issue**
1. Start the server

**Log files**
[17:35:16] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.8
[17:35:16] [main/WARN]: Mod resolution failed
[17:35:16] [main/INFO]: Immediate reason: [HARD_DEP_NO_CANDIDATE vcinteraction 1.19-1.0.1 {depends fabric @ [>=0.55.1+1.19]}, ROOT_FORCELOAD_SINGLE vcinteraction 1.19-1.0.1]
[17:35:16] [main/INFO]: Reason: [HARD_DEP vcinteraction 1.19-1.0.1 {depends fabric @ [>=0.55.1+1.19]}]
[17:35:16] [main/INFO]: SERVER environment disabled: [fabric-key-binding-api-v1]
[17:35:16] [main/INFO]: Fix: add [add:fabric 0.55.1+1.19 ([[0.55.1+1.19,∞)])], remove [], replace []
[17:35:16] [main/ERROR]: Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
         - Install fabric, version 0.55.1+1.19 or later.
Unmet dependency listing:
         - Mod 'Voice Chat Interaction' (vcinteraction) 1.19-1.0.1 requires version 0.55.1+1.19 or later of fabric, which is missing!
        at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.8.jar:?]
        at net.fabricmc.installer.ServerLauncher.main(ServerLauncher.java:69) [server.jar:0.11.0]

**Versions**
- Minecraft version 1.19
- Fabric loader version 0.14.8-1.19
- Mod version 1.19-1.0.1
- Simple Voice Chat 1.19-2.2.46

**Other mods**
Lithium 1.19-0.8.0
Phosphor 1.19-0.8.1

**Comment by kason-i** [comment]
Installed fabric API and it is working now!
